# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62dcf791f2cc78cfe7348cb4d16654c7ee35babcac881bd61b72d4bfae61bf55bd46f503efb907fe7468dc06a08a4d6ce968c964c88fd00cad84b99e4295ffeb

test:
  secret_key_base: 62f899a43e358687fb4fa5b1eb308b9925e83ac0f95c70b15e41734d9bd26768d0d00279534dc1e6ae3e847c856c0a6c9a45cb591d170f3237754b6c22ff317a

production:
  secret_key_base: 62f899a43e358687fb4fa5b1eb308b9925e83ac0f95c70b15e41734d9bd26768d0d00279534dc1e6ae3e847c856c0a6c9a45cb591d170f3237754b6c22ff317a

# Do not keep production secrets in the repository,
# instead read values from the environment.
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
